// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD0fDjn2XBq35XYQoeojxJXEhN4_MG3RGg',
    appId: '1:776285847170:web:ba81cd1ae6372830ebfe9b',
    messagingSenderId: '776285847170',
    projectId: 'twsylh',
    authDomain: 'twsylh.firebaseapp.com',
    storageBucket: 'twsylh.firebasestorage.app',
    measurementId: 'G-WY2PR2GM0H',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDs8Zn4zZFlClmOEKRY8I4t2CMJUOEVjKs',
    appId: '1:776285847170:android:4b931c5b9979176bebfe9b',
    messagingSenderId: '776285847170',
    projectId: 'twsylh',
    storageBucket: 'twsylh.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDCVyMKgr5QDxS8AIJdvhsJNW6RzbTuee0',
    appId: '1:776285847170:ios:ad4e1306739a0081ebfe9b',
    messagingSenderId: '776285847170',
    projectId: 'twsylh',
    storageBucket: 'twsylh.firebasestorage.app',
    iosClientId: '776285847170-r6e0n7g80p09eqhae2gdm30r9vq6d3cr.apps.googleusercontent.com',
    iosBundleId: 'com.twsylh.user',
  );
}
